name = "Cave Game"
author = "TheMicCraft"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "eaad61ced2c6ac69f47321f3318807f86d9e582fbb8da39b255549fcb24f84be"

[versions]
fabric = "0.19.3"
minecraft = "1.21.11"
