name = "Cave Game"
author = "TheMicCraft"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b9916769cfb146328bdf636d08aafef4da5dab5ce27100983266f661951335f3"

[versions]
fabric = "0.19.3"
minecraft = "1.21.11"
