name = "Cave Game"
author = "TheMicCraft"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "ff429c1c9b3fd3f218bd0de875203d09f3204053b2a5d6846f15ad73d24b27a0"

[versions]
fabric = "0.19.5"
minecraft = "1.21.11"
